name: Python CI and Testing Automation with GitHub Actions

on:
  push:
    branches:
      - Master
env:
  PYTHON_VERSION: 3.12.3
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
